package com.app.our.cskies.model

data class Cityes(
    val cityes:List<String> = listOf(
    "United States",
    "Canada",
        "Turkey","تركيا",
    "Afghanistan",
    "Albania",
    "Algeria",
    "American Samoa",
    "Andorra",
    "Angola",
    "Anguilla",
    "Antarctica",
    "Antigua",
    "Argentina",
    "Armenia",
    "Aruba",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Barbuda",
    "Bermuda",
    "Bhutan",
    "Bolivia",
    "Bosnia and Herzegovina",
    "Botswana",
    "Bouvet Island",
    "Brazil",
    "British Indian Ocean Territory",
    "Brunei Darussalam",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Cambodia",
    "Cameroon",
    "Cape Verde",
    "Cayman Islands",
    "Central African Republic",
    "Chad",
    "Chile",
    "China",
    "Christmas Island",
    "Cocos (Keeling) Islands",
    "Colombia",
    "Comoros",
    "Congo",
    "Cook Islands",
    "Costa Rica",
    "Croatia (Hrvatska)",
    "Cuba",
    "Cyprus",
    "Czech Republic",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "East Timor",
    "Ecudaor",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Ethiopia",
    "Falkland Islands (Malvinas)",
    "Faroe Islands",
    "Fiji",
    "Finland",
    "France",
    "France, Metropolitan",
    "French Guiana",
    "French Polynesia",
    "French Southern Territories",
    "Gabon",
    "Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Gibraltar",
    "Greece",
    "Greenland",
    "Grenada",
    "Guadeloupe",
    "Guam",
    "Guatemala",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Heard and Mc Donald Islands",
    "Honduras",
    "Hong Kong",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran (Islamic Republic of)",
    "Iraq",
    "Ireland",
    "Israel",
    "Italy",
    "Ivory Coast",
    "Jamaica",
    "Japan",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "Korea, Democratic People's Republic of",
    "Korea, Republic of",
    "Kosovo",
    "Kuwait",
    "Kyrgyzstan",
    "Lao People's Democratic Republic",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libyan Arab Jamahiriya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Macau",
    "Macedonia",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Marshall Islands",
    "Martinique",
    "Mauritania",
    "Mauritius",
    "Mayotte",
    "Mexico",
    "Micronesia, Federated States of",
    "Moldova, Republic of",
    "Monaco",
    "Mongolia",
    "Montserrat",
    "Morocco",
    "Mozambique",
    "Myanmar",
    "Namibia",
    "Nauru",
    "Nepal",
    "Netherlands",
    "Netherlands Antilles",
    "New Caledonia",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "Niue",
    "Norfork Island",
    "Northern Mariana Islands",
    "Norway",
    "Oman",
    "Pakistan",
    "Palau",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Pitcairn",
    "Poland",
    "Portugal",
    "Puerto Rico",
    "Qatar",
    "Reunion",
    "Romania",
    "Russian Federation",
    "Rwanda",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Saint Vincent and the Grenadines",
    "Samoa",
    "San Marino",
    "Sao Tome and Principe",
    "Saudi Arabia",
    "Senegal",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "South Georgia South Sandwich Islands",
    "South Sudan",
    "Spain",
    "Sri Lanka",
    "St. Helena",
    "St. Pierre and Miquelon",
    "Sudan",
    "Suriname",
    "Svalbarn and Jan Mayen Islands",
    "Swaziland",
    "Sweden",
    "Switzerland",
    "Syrian Arab Republic",
    "Taiwan",
    "Tajikistan",
    "Tanzania, United Republic of",
    "Thailand",
    "Togo",
    "Tokelau",
    "Tonga",
    "Trinidad and Tobago",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Turks and Caicos Islands",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom",
    "United States minor outlying islands",
    "Uruguay",
    "Uzbekistan",
    "Vanuatu",
    "Vatican City State",
    "Venezuela",
    "Vietnam",
    "Virigan Islands (British)",
    "Virgin Islands (U.S.)",
    "Wallis and Futuna Islands",
    "Western Sahara",
    "Yemen",
    "Yugoslavia",
    "Zaire",
    "Zambia",
    "Zimbabwe",
        "الولايات المتحدة",
        "كندا",
        "أفغانستان" ,
        "ألبانيا" ,
        "الجزائر",
        "ساموا الأمريكية",
        "أندورا",
        "أنغولا" ,
        "أنغيلا",
        "أنتاركتيكا",
        "أنتيغوا",
        "الأرجنتين" ,
        "أرمينيا" ,
        "أروبا",
        "أستراليا" ,
        "النمسا" ,
        "أذربيجان",
        "جزر البهاما" ,
        "البحرين",
        "بنغلاديش" ,
        "بربادوس" ,
        "بيلاروس" ,
        "بلجيكا" ,
        "بليز" ,
        "بنن",
        "باربودا",
        "برمودا",
        "بوتان" ,
        "بوليفيا" ,
        "البوسنة والهرسك",
        "بوتسوانا" ,
        "جزيرة بوفيت" ,
        "البرازيل",
        "إقليم المحيط البريطاني الهندي",
        "بروناي دار السلام",
        "بلغاريا" ,
        "بوركينا فاسو",
        "بوروندي" ,
        "كمبوديا" ,
        "الكاميرون" ,
        "الرأس الأخضر" ,
        "جزر كايمان" ,
        "جمهورية افريقيا الوسطى",
        "تشاد" ,
        "شيلي" ,
        "الصين",
        "جزيرة الكريسماس" ,
        "جزر كوكوس (كيلينغ)" ,
        "كولومبيا" ,
        "جزر القمر" ,
        "الكونغو" ,
        "جزر كوك",
        "كوستا ريكا",
        "كرواتيا (هرفاتسكا)" ,
        "كوبا" ,
        "قبرص" ,
        "الجمهورية التشيكية",
        "الدنمارك" ,
        "جيبوتي" ,
        "دومينيكا",
        "جمهورية الدومينيكان",
        "تيمور الشرقية",
        "Ecudaor" ,
        "مصر",
        "السلفادور",
        "غينيا الإستوائية",
        "إريتريا" ,
        "إستونيا" ,
        "أثيوبيا",
        "جزر فوكلاند (مالفيناس)" ,
        "جزر فاروس",
        "فيجي" ,
        "فنلندا",
        "فرنسا",
        "فرنسا , متروبوليتان" ,
        "غيانا الفرنسية",
        "بولينيزيا الفرنسية",
        "المناطق الجنوبية لفرنسا",
        "غابون" ,
        "غامبيا" ,
        "جورجيا" ,
        "ألمانيا",
        "غانا" ,
        "جبل طارق" ,
        "اليونان",
        "الأرض الخضراء",
        "غرينادا",
        "جوادلوب",
        "غوام" ,
        "غواتيمالا" ,
        "غينيا" ,
        "غينيا - بيساو" ,
        "غيانا" ,
        "هايتي" ,
        "جزر هيرد وماكدونالد" ,
        "هندوراس" ,
        "هونغ كونغ" ,
        "هنغاريا",
        "أيسلندا",
        "الهند",
        "إندونيسيا",
        "إيران (جمهورية - الإسلامية)" ,
        "العراق",
        "أيرلندا" ,
        "إسرائيل",
        "إيطاليا",
        "ساحل العاج",
        "جامايكا" ,
        "اليابان",
        "الأردن",
        "كازاخستان" ,
        "كينيا" ,
        "كيريباتي" ,
        "كوريا, الجمهورية الشعبية الديمقراطية",
        "جمهورية كوريا",
        "كوسوفو" ,
        "الكويت",
        "قيرغيزستان" ,
        "جمهورية لاو الديمقراطية الشعبية" ,
        "لاتفيا" ,
        "لبنان" ,
        "ليسوتو" ,
        "ليبيريا" ,
        "الجماهيرية العربية الليبية",
        "ليختنشتاين" ,
        "ليتوانيا" ,
        "لوكسمبورغ" ,
        "ماكاو",
        "مقدونيا" ,
        "مدغشقر" ,
        "ملاوي" ,
        "ماليزيا" ,
        "جزر المالديف" ,
        "مالي" ,
        "مالطا" ,
        "جزر مارشال" ,
        "مارتينيك",
        "موريتانيا" ,
        "موريشيوس" ,
        "مايوت" ,
        "المكسيك" ,
        "ولايات ميكرونيزيا الموحدة" ,
        "جمهورية مولدوفا",
        "موناكو" ,
        "منغوليا" ,
        "مونتسيرات",
        "المغرب",
        "موزامبيق" ,
        "ميانمار" ,
        "ناميبيا" ,
        "ناورو" ,
        "نيبال" ,
        "هولندا",
        "جزر الأنتيل الهولندية",
        "كاليدونيا الجديدة",
        "نيوزيلندا",
        "نيكاراغوا" ,
        "النيجر" ,
        "نيجيريا",
        "نيوي",
        "جزيرة نورفورك" ,
        "جزر مريانا الشمالية",
        "النرويج",
        "سلطنة عمان",
        "باكستان" ,
        "بالاو" ,
        "بنما" ,
        "بابوا غينيا الجديدة" ,
        "باراغواي" ,
        "بيرو",
        "فيلبيني",
        "بيتكيرن" ,
        "بولندا",
        "البرتغال",
        "بورتوريكو" ,
        "دولة قطر",
        "جمع شمل",
        "رومانيا",
        "الاتحاد الروسي" ,
        "رواندا" ,
        "سانت كيتس ونيفيس",
        "القديسة لوسيا",
        "سانت فنسنت وجزر غرينادين",
        "ساموا" ,
        "سان مارينو",
        "سان تومي وبرينسيبي" ,
        "المملكة العربية السعودية",
        "السنغال",
        "سيشيل" ,
        "سيرا ليون",
        "سنغافورة" ,
        "سلوفاكيا" ,
        "سلوفينيا" ,
        "جزر سليمان",
        "الصومال",
        "جنوب أفريقيا",
        "جزر ساوث جورجيا الجنوبية ساندويتش" ,
        "جنوب السودان",
        "إسبانيا",
        "سيريلانكا",
        "سانت هيلانة" ,
        "سانت بيير وميكلون" ,
        "السودان",
        "سورينام",
        "جزر سفالبارن وجان ماين" ,
        "سوازيلند" ,
        "السويد",
        "سويسرا" ,
        "الجمهورية العربية السورية",
        "تايوان" ,
        "طاجيكستان" ,
        "جمهورية تنزانيا المتحدة" ,
        "تايلاند" ,
        "توجو",
        "توكيلاو" ,
        "تونغا" ,
        "ترينداد وتوباغو",
        "تونس" ,
        "ديك رومى",
        "تركمانستان" ,
        "جزر تركس وكايكوس",
        "توفالو",
        "أوغندا" ,
        "أوكرانيا" ,
        "الإمارات العربية المتحدة",
        "المملكة المتحدة",
        "جزر الولايات المتحدة البعيدة الصغرى",
        "أوروغواي" ,
        "أوزبكستان" ,
        "فانواتو" ,
        "دولة الفاتيكان" ,
        "فنزويلا" ,
        "فيتنام",
        "جزر فيريغان (البريطانية)" ,
        "جزر فيرجن (الولايات المتحدة)" ,
        "جزر واليس وفوتونا" ,
        "الصحراء الغربية",
        "اليمن",
        "يوغوسلافيا" ,
        "زائير" ,
        "زامبيا" ,
        "زمبابوي"
    )
    )
